### ISSUE TITLE
missing train_test_split.json

### ISSUE THREAD

**Issue by redhatdb** [db-tu-dresden/FASTgres-PVLDBv16#1]
We current test the algorithm in IMDB, but the split file is missing.

Thanks!

**Comment by KiraThiessat** [comment]
Hi there and sorry for the late reply. I assume the issue you are encountering is within `evaluate_queries.py`. You can easily create your own split file by just having a dictionary with two keys "train"  and "test", where both values are lists of strings. For your IMDB scenario this might looks like this:

split:
    "train": ["1a.sql", "1b.sql", ...]
    "test": ["10a.sql", "10b.sql", ...]

Let me know if you need any more assistance!

**Comment by KiraThiessat** [comment]
Closing this issue. If any more questions arise, feel free to open another one.
